name: Go Test

on:
  workflow_call:
    inputs:
      go-version:
        type: string
        default: "1.22.2"
      uses-goreleaser:
        type: boolean
        default: true
      goreleaser-version:
        type: string
        default: "latest"

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4.2.0

      - name: Setup Go
        uses: actions/setup-go@v5.0.2
        with:
          go-version: ${{ inputs.go-version }}

      - name: Run tests
        run: |
          go test ./...

      - name: Check GoReleaser
        if: inputs.uses-goreleaser
        uses: goreleaser/goreleaser-action@v5.1.0
        with:
          version: ${{ inputs.goreleaser-version }}
          args: build --clean --snapshot
  govulncheck:
    runs-on: ubuntu-20.04

    steps:
      - name: govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-version-input: ${{ inputs.go-version }}
