name: Go Test

on:
  workflow_call:
    inputs:
      go-version:
        type: string
      go-version-file:
        type: string
      uses-goreleaser:
        type: boolean
        default: true
      goreleaser-version:
        type: string
        default: "~> v2"
      include-govulncheck:
        type: boolean
        default: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Setup Go
        uses: actions/setup-go@v5.5.0
        with:
          go-version: ${{ inputs.go-version }}
          go-version-file: ${{ inputs.go-version-file }}

      - name: Run tests
        run: |
          go test ./...

      - name: Check GoReleaser
        if: inputs.uses-goreleaser
        uses: goreleaser/goreleaser-action@v6.3.0
        with:
          version: ${{ inputs.goreleaser-version }}
          args: build --clean --snapshot
  govulncheck:
    runs-on: ubuntu-latest

    steps:
      - name: govulncheck
        uses: golang/govulncheck-action@v1
        if: inputs.include-govulncheck
        with:
          go-version-input: ${{ inputs.go-version }}
          go-version-file: ${{ inputs.go-version-file }}
