name: Go Test

on:
  workflow_call:
    inputs:
      go-version:
        type: string
        default: "1.23"
      uses-goreleaser:
        type: boolean
        default: true
      goreleaser-version:
        type: string
        default: "latest"
      # Borrowed from https://github.com/golang/govulncheck-action/blob/master/action.yml
      # since they were using an old version of setup-go
      govuln-output-format:
        description: 'The format of the output'
        required: false
        default: 'text'
      govuln-go-package:
        description: 'Go Package to scan with govulncheck'
        required: false
        default: './...'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Setup Go
        uses: actions/setup-go@v5.3.0
        with:
          go-version: ${{ inputs.go-version }}

      - name: Run tests
        run: |
          go test ./...

      - name: Check GoReleaser
        if: inputs.uses-goreleaser
        uses: goreleaser/goreleaser-action@v5.1.0
        with:
          version: ${{ inputs.goreleaser-version }}
          args: build --clean --snapshot

      # Borrowed from https://github.com/golang/govulncheck-action/blob/master/action.yml
      # since they were using an old version of setup-go
      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest
      - name: Run govulncheck
        run: govulncheck -C . -format ${{ inputs.govuln-output-format }} ${{ inputs.govuln-go-package }}
