name: Issues and PRs Notify Discord
on:
  workflow_call:
    inputs:
      triageLabel:
        type: string
        default: needs triage
      discussionLabel:
        type: string
        default: discussion
    secrets:
      discordWebhook:
        required: true

jobs:
  labelNotify:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Overview
        env:
          ACTION: ${{ github.event.action }}
          TITLE: ${{ github.event.issue.title || github.event.pull_request.title || github.event.release.name }}
          NUMBER: ${{ github.event.issue.number || github.event.pull_request.number || github.event.release.id }}
          LABELS: ${{ join(github.event.issue.labels.*.name, ', ') || join(github.event.pull_request.labels.*.name, ', ') }}
          CHANGED_LABEL: ${{ github.event.label.name }}
          URL: ${{ github.event.issue.html_url || github.event.pull_request.html_url || github.event.release.html_url }}
          REPO: ${{ github.event.repository.full_name }}
        run: |
          echo "issueTitleLink=[$TITLE (#$NUMBER)](<$URL>) in $REPO" >> $GITHUB_ENV
          echo "releaseTitleLink=[$TITLE](<$URL>) in $REPO" >> $GITHUB_ENV
          echo "Action $ACTION for $TITLE ($NUMBER) in $REPO"

      - name: Bug reported
        if: github.event.action == 'opened' && contains(github.event.issue.labels.*.name, 'bug')

        uses: appleboy/discord-action@v1.2.0
        with:
          webhook_url: ${{ secrets.discordWebhook }}
          message: "🪳 A bug has been reported: ${{env.issueTitleLink}}"

      - name: Enhancement requested
        if: github.event.action == 'opened' && contains(github.event.issue.labels.*.name, 'enhancement')
        uses: appleboy/discord-action@v1.2.0
        with:
          webhook_url: ${{ secrets.discordWebhook }}
          message: "🎁 An enhancement has been requested: ${{env.issueTitleLink}}"

      - name: Help wanted
        if: github.event.action == 'labeled' && github.event.label.name == 'help wanted'
        uses: appleboy/discord-action@v1.2.0
        with:
          webhook_url: ${{ secrets.discordWebhook }}
          message: "🙌 Help is wanted: ${{env.issueTitleLink}}"

      - name: Start discussion
        if: github.event.action == 'labeled' && github.event.label.name == inputs.discussionLabel
        uses: appleboy/discord-action@v1.2.0
        with:
          webhook_url: ${{ secrets.discordWebhook }}
          message: "💬 Let's discuss: ${{env.issueTitleLink}}"

      - name: Triaged
        if: github.event.action == 'unlabeled' && github.event.label.name == inputs.triageLabel
        uses: appleboy/discord-action@v1.2.0
        with:
          webhook_url: ${{ secrets.discordWebhook }}
          message: "🩺 Issue has been triaged: ${{env.issueTitleLink}}"

      - name: Completed
        if: github.event.action == 'closed' && github.event.issue.state_reason == 'completed'
        uses: appleboy/discord-action@v1.2.0
        with:
          webhook_url: ${{ secrets.discordWebhook }}
          message: "🎉 Issue has been resolved: ${{env.issueTitleLink}}"

      - name: Pull Request merged
        if: |
          github.event.action == 'closed' 
          && github.event.pull_request.merged == true
          && !contains(github.event.pull_request.labels.*.name, 'dependencies')
        uses: appleboy/discord-action@v1.2.0
        with:
          webhook_url: ${{ secrets.discordWebhook }}
          message: "🚀 Pull Request merged: ${{ env.issueTitleLink }}"

      - name: Release released
        if: github.event.action == 'released'
        uses: appleboy/discord-action@v1.2.0
        with:
          webhook_url: ${{ secrets.discordWebhook }}
          message: "🏷️ A new release has been published: ${{ env.releaseTitleLink }}"