on:
  workflow_call:
    inputs:
      image-repo:
        type: string
        required: true
      image-platforms:
        type: string
        default: "linux/amd64,linux/arm64"
        description: "Docker buildx platforms comma-separated, such as linux/amd64,linux/arm64"
      image-push:
        type: boolean
        default: true
      extra-gradle-tasks:
        type: string
        description: "Such as test"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0

      - name: Login to image registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Gradle build and push
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            -PimageRepo=${{ inputs.image-repo }}
            -PimagePlatforms=${{ inputs.image-platform }}
            -PimagePush=${{ inputs.image-push }} 
            -PimageCacheFrom=type=gha
            -PimageCacheTo=type=gha,mode=max
            ${{ inputs.extra-gradle-tasks }}
            buildSimpleBootImage
